replicaCount: 1

image:
  repository: traefik
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  ports:
    web:
      port: 80
    websecure:
      port: 443

# Configuration des Entrypoints et des Routes pour Traefik
entrypoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
